### ISSUE TITLE
Style for checkboxes & hr

### ISSUE THREAD

**Issue by Flashwalker** [tobealive/trilum-eote-theme#6]
Hi. I made the style for checkboxes:
``` diff
...
/* ==[ 1.2. General Fixes ]== */
/* Scrollbars */
#root-widget ::-webkit-scrollbar {
	width: 8px;
}
#root-widget ::-webkit-scrollbar-thumb {
	border-width: 0;
	border-radius: 0;
	background: var(--hover-item-background-color);
}
+++
+++/* Checkboxes */
+++#root-widget input[type=checkbox] {
+++    /*display: none;*/
+++    width: 0;
+++    height: 0;
+++    margin-right: 22px;
+++    position: relative;
+++    text-align: center;
+++}
+++#root-widget input[type=checkbox]:focus {
+++    box-shadow: none;
+++    outline: none;
+++}
+++#root-widget input[type=checkbox]::before {
+++    content: '';
+++    position: relative;
+++    top: -16px;
+++    display: block;
+++    width: 20px;
+++    height: 20px;
+++    border: 1px solid var(--hover-item-background-color);
+++    background: var(--main-background-color);
+++    box-sizing: content-box;
+++}
+++#root-widget input[type=checkbox]:checked::before {
+++    border: 1px solid var(--link-color);
+++    background: var(--main-border-color);
+++}
+++#root-widget input[type=checkbox]::after {
+++    content: '✓';
+++    text-indent: 4px;
+++    position: absolute;
+++    top: -17px;
+++    display: none;
+++    width: 20px;
+++    height: 20px;
+++    box-sizing: content-box;
+++    text-align: center;
+++}
+++#root-widget input[type=checkbox]:checked::after {
+++    display: block;
+++    color: var(--link-color);
+++}

/* Cursors */
...
```
![image](https://user-images.githubusercontent.com/2188215/210798651-0f54379e-6d92-4bf0-b48c-7e2bba9f80dc.png)

Also fo `<hr>`:
```diff
...
+++
+++/* hr */
+++#root-widget hr {
+++    border: 0;
+++    height: 1px;
+++    background: linear-gradient(to right, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.45) 50%, rgba(255, 255, 255, 0) 100%);
+++    text-align: center    
+++}

/* Cursors */
...
```
![image](https://user-images.githubusercontent.com/2188215/210810356-fbd8fb17-af7f-4113-b9db-d585dbd07950.png)

**Comment by Flashwalker** [comment]
```css
/* Checkboxes */
#root-widget input[type=checkbox] {
    /*display: none;*/
    width: 0;
    height: 0;
    margin-right: 22px;
    position: relative;
    text-align: center;
}
#root-widget input[type=checkbox]:focus {
    box-shadow: none;
    outline: none;
}
#root-widget input[type=checkbox]::before {
    content: '';
    position: relative;
    top: -16px;
    display: block;
    width: 20px;
    height: 20px;
    border: 1px solid var(--hover-item-background-color);
    background: var(--main-background-color);
    box-sizing: content-box;
}
#root-widget input[type=checkbox]:checked::before {
    border: 1px solid var(--link-color);
    background: var(--main-border-color);
}
#root-widget input[type=checkbox]::after {
    content: '✓';
    text-indent: 4px;
    position: absolute;
    top: -17px;
    display: none;
    width: 20px;
    height: 20px;
    box-sizing: content-box;
    text-align: center;
}
#root-widget input[type=checkbox]:checked::after {
    display: block;
    color: var(--link-color);
}
```

**Comment by Flashwalker** [comment]
```css
/* hr */
#root-widget hr {
    border: 0;
    height: 1px;
    background: linear-gradient(to right, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.45) 50%, rgba(255, 255, 255, 0) 100%);
    text-align: center    
}
```
